import { CostcoReceipt } from '../types';

export const SAMPLE_COSTCO_RECEIPTS: CostcoReceipt[] = [
  {
    id: 'rcpt_wh_1',
    orderNumber: '00471 0023 00894',
    orderDate: '2024-10-14',
    orderType: 'Warehouse',
    warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
    paymentCard: 'Costco Anywhere Visa ****4128',
    subtotal: 138.92,
    tax: 12.85,
    total: 151.77,
    sourceType: 'sample',
    fileName: 'sample_foster_city_receipt.jpg',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    items: [
      {
        id: 'item_1_1',
        itemId: '1142277',
        rawName: 'KS ORG EVOO 2L',
        productName: 'Kirkland Signature Organic Extra Virgin Olive Oil, 2 L',
        brand: 'Kirkland Signature',
        category: 'Pantry & Oils',
        description: 'USDA certified organic cold-extracted extra virgin olive oil in a 2-liter bottle, harvested from Mediterranean olives.',
        packageDetails: '2 Liters (67.6 fl oz)',
        quantity: 1,
        unitPrice: 21.99,
        totalPrice: 21.99,
        orderId: 'rcpt_wh_1',
        orderNumber: '00471 0023 00894',
        orderDate: '2024-10-14',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/kirkland-signature-organic-extra-virgin-olive-oil%2c-2-l.product.100334842.html',
        isEnriched: true,
      },
      {
        id: 'item_1_2',
        itemId: '2010',
        rawName: 'ROTISSERIE CHICKEN',
        productName: 'Kirkland Signature Fresh Roasted Rotisserie Chicken',
        brand: 'Kirkland Signature',
        category: 'Fresh Deli & Meat',
        description: 'Costco staple 3 lb whole roasted chicken seasoned and hot from the rotisserie.',
        packageDetails: '3 lbs approx',
        quantity: 1,
        unitPrice: 4.99,
        totalPrice: 4.99,
        orderId: 'rcpt_wh_1',
        orderNumber: '00471 0023 00894',
        orderDate: '2024-10-14',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.google.com/search?q=Costco+item+2010+rotisserie+chicken',
        isEnriched: true,
      },
      {
        id: 'item_1_3',
        itemId: '1714597',
        rawName: 'KS CREATE-A-SIZE PT 12CT',
        productName: 'Kirkland Signature Create-a-Size Paper Towels, 12 Rolls',
        brand: 'Kirkland Signature',
        category: 'Household & Paper Goods',
        description: '12 rolls of 2-ply premium embossed paper towels with 160 sheets per roll.',
        packageDetails: '12 Rolls / 160 Sheets',
        quantity: 1,
        unitPrice: 22.99,
        totalPrice: 22.99,
        orderId: 'rcpt_wh_1',
        orderNumber: '00471 0023 00894',
        orderDate: '2024-10-14',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/kirkland-signature-paper-towels.product.100845341.html',
        isEnriched: true,
      },
      {
        id: 'item_1_4',
        itemId: '1094091',
        rawName: "RAO'S MARINARA 2/28OZ",
        productName: "Rao's Homemade Marinara Pasta Sauce, 28 oz, 2-pack",
        brand: "Rao's Homemade",
        category: 'Pantry & Pasta',
        description: 'Slow-simmered Italian plum tomato sauce made with sweet Italian olive oil, fresh garlic, and basil.',
        packageDetails: '2 x 28 oz Jars',
        quantity: 2,
        unitPrice: 11.99,
        totalPrice: 23.98,
        discount: 4.00,
        orderId: 'rcpt_wh_1',
        orderNumber: '00471 0023 00894',
        orderDate: '2024-10-14',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/raos-homemade-marinara-sauce.product.100685606.html',
        isEnriched: true,
      },
      {
        id: 'item_1_5',
        itemId: '30669',
        rawName: 'ORGANIC BANANAS 3LB',
        productName: 'Organic Fresh Cavendish Bananas, 3 lb Bunch',
        brand: 'Del Monte / Chiquita',
        category: 'Fresh Produce',
        description: 'USDA Certified Organic fresh yellow bananas in a 3-pound bunch.',
        packageDetails: '3 lbs',
        quantity: 1,
        unitPrice: 1.99,
        totalPrice: 1.99,
        orderId: 'rcpt_wh_1',
        orderNumber: '00471 0023 00894',
        orderDate: '2024-10-14',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.google.com/search?q=Costco+item+30669+organic+bananas',
        isEnriched: true,
      },
    ],
  },
  {
    id: 'rcpt_online_1',
    orderNumber: '3104882910',
    orderDate: '2024-11-28',
    orderType: 'Online',
    warehouseLocation: 'Costco.com (Shipped Order)',
    paymentCard: 'Costco Anywhere Visa ****4128',
    subtotal: 799.98,
    tax: 72.00,
    total: 871.98,
    sourceType: 'sample',
    fileName: 'costco_online_cyberweek_order.json',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 75).toISOString(),
    items: [
      {
        id: 'item_2_1',
        itemId: '1462000',
        rawName: 'SONOS ARC SOUNDBAR BLK',
        productName: 'Sonos Arc Wireless Smart Soundbar with Dolby Atmos (Black)',
        brand: 'Sonos',
        category: 'Electronics & Audio',
        description: 'Premium smart soundbar for TV, movies, music, and gaming featuring 3D Dolby Atmos sound with Costco bonus voucher.',
        packageDetails: 'Includes $40 Apple Gift Card / Wall Mount discount bundle',
        quantity: 1,
        unitPrice: 699.99,
        totalPrice: 699.99,
        discount: 100.00,
        orderId: 'rcpt_online_1',
        orderNumber: '3104882910',
        orderDate: '2024-11-28',
        orderType: 'Online',
        warehouseLocation: 'Costco.com (Shipped Order)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/sonos-arc-soundbar.product.100661642.html',
        isEnriched: true,
      },
      {
        id: 'item_2_2',
        itemId: '1682390',
        rawName: 'APPLE AIRPODS PRO 2 USB-C',
        productName: 'Apple AirPods Pro (2nd Generation) with MagSafe Case (USB-C)',
        brand: 'Apple',
        category: 'Electronics & Wearables',
        description: 'Active Noise Cancellation, Transparency mode, Personalized Spatial Audio, and AppleCare+ eligible bundle.',
        packageDetails: 'USB-C Charging Case included',
        quantity: 1,
        unitPrice: 199.99,
        totalPrice: 199.99,
        orderId: 'rcpt_online_1',
        orderNumber: '3104882910',
        orderDate: '2024-11-28',
        orderType: 'Online',
        warehouseLocation: 'Costco.com (Shipped Order)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/apple-airpods-pro-2nd-generation.product.4000216709.html',
        isEnriched: true,
      },
    ],
  },
  {
    id: 'rcpt_wh_2',
    orderNumber: '00122 0041 00382',
    orderDate: '2025-01-18',
    orderType: 'Warehouse',
    warehouseLocation: 'Costco Wholesale #122 (San Jose, CA)',
    paymentCard: 'Chase Sapphire Visa ****8931',
    subtotal: 214.47,
    tax: 19.84,
    total: 234.31,
    sourceType: 'sample',
    fileName: 'warehouse_receipt_jan2025.csv',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 24).toISOString(),
    items: [
      {
        id: 'item_wh2_1',
        itemId: '1643444',
        rawName: 'KS 3PC WEDGE SET RH',
        productName: 'Kirkland Signature 3-Piece Golf Wedge Set (Right Hand)',
        brand: 'Kirkland Signature',
        category: 'Sports & Outdoors',
        description: 'Milled face golf wedge set (52° Gap, 56° Sand, 60° Lob) designed with True Temper steel shafts.',
        packageDetails: 'Set of 3 Wedges (52, 56, 60)',
        quantity: 1,
        unitPrice: 169.99,
        totalPrice: 169.99,
        orderId: 'rcpt_wh_2',
        orderNumber: '00122 0041 00382',
        orderDate: '2025-01-18',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #122 (San Jose, CA)',
        paymentCard: 'Chase Sapphire Visa ****8931',
        webSourceUrl: 'https://www.costco.com/kirkland-signature-3-piece-golf-wedge-set.product.100696718.html',
        isEnriched: true,
      },
      {
        id: 'item_wh2_2',
        itemId: '1337424',
        rawName: 'KS BATH TISSUE 30PK',
        productName: 'Kirkland Signature 2-Ply Bath Tissue, 30 Rolls',
        brand: 'Kirkland Signature',
        category: 'Household & Paper Goods',
        description: 'Thick, absorbent, wide-sheet 2-ply toilet paper with 380 sheets per roll (1,140 sq ft total).',
        packageDetails: '30 Rolls (380 Sheets/Roll)',
        quantity: 1,
        unitPrice: 22.49,
        totalPrice: 22.49,
        orderId: 'rcpt_wh_2',
        orderNumber: '00122 0041 00382',
        orderDate: '2025-01-18',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #122 (San Jose, CA)',
        paymentCard: 'Chase Sapphire Visa ****8931',
        webSourceUrl: 'https://www.costco.com/kirkland-signature-bath-tissue.product.100845340.html',
        isEnriched: true,
      },
      {
        id: 'item_wh2_3',
        itemId: '1142277',
        rawName: 'KS ORG EVOO 2L',
        productName: 'Kirkland Signature Organic Extra Virgin Olive Oil, 2 L',
        brand: 'Kirkland Signature',
        category: 'Pantry & Oils',
        description: 'USDA certified organic cold-extracted extra virgin olive oil in a 2-liter bottle.',
        packageDetails: '2 Liters (67.6 fl oz)',
        quantity: 1,
        unitPrice: 21.99,
        totalPrice: 21.99,
        orderId: 'rcpt_wh_2',
        orderNumber: '00122 0041 00382',
        orderDate: '2025-01-18',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #122 (San Jose, CA)',
        paymentCard: 'Chase Sapphire Visa ****8931',
        webSourceUrl: 'https://www.costco.com/kirkland-signature-organic-extra-virgin-olive-oil%2c-2-l.product.100334842.html',
        isEnriched: true,
      },
    ],
  },
  {
    id: 'rcpt_gc_1',
    orderNumber: '3109928114',
    orderDate: '2025-01-28',
    orderType: 'Online',
    warehouseLocation: 'Costco.com (Digital Delivery)',
    paymentCard: 'Costco Anywhere Visa ****4128',
    subtotal: 689.96,
    tax: 0.00,
    total: 689.96,
    sourceType: 'sample',
    fileName: 'costco_giftcards_order.json',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    items: [
      {
        id: 'item_gc_1',
        itemId: '1579294',
        rawName: 'DOORDASH $100 EGIFT 4X25',
        productName: 'DoorDash $100 eGift Card (4 x $25)',
        brand: 'DoorDash',
        category: 'Gift Cards',
        description: 'Costco wholesale discounted electronic gift cards for DoorDash restaurant and food delivery.',
        packageDetails: '4 x $25 Digital eGift Cards ($100 Value)',
        quantity: 1,
        unitPrice: 79.99,
        totalPrice: 79.99,
        discount: 20.00,
        orderId: 'rcpt_gc_1',
        orderNumber: '3109928114',
        orderDate: '2025-01-28',
        orderType: 'Online',
        warehouseLocation: 'Costco.com (Digital Delivery)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/doordash-gift-cards.html',
        isEnriched: true,
      },
      {
        id: 'item_gc_2',
        itemId: '1456100',
        rawName: 'AIR CANADA $500 EGIFT CARD',
        productName: 'Air Canada $500 Electronic Gift Card',
        brand: 'Air Canada',
        category: 'Gift Cards',
        description: 'Costco wholesale discounted Air Canada airline flight travel gift card voucher.',
        packageDetails: '$500 Electronic Travel Voucher',
        quantity: 1,
        unitPrice: 449.99,
        totalPrice: 449.99,
        discount: 50.01,
        orderId: 'rcpt_gc_1',
        orderNumber: '3109928114',
        orderDate: '2025-01-28',
        orderType: 'Online',
        warehouseLocation: 'Costco.com (Digital Delivery)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.ca/air-canada-egift-card.html',
        isEnriched: true,
      },
      {
        id: 'item_gc_3',
        itemId: '1694200',
        rawName: 'SKIPTHEDISHES $100 GIFT CARD',
        productName: 'SkipTheDishes $100 Gift Card (2 x $50)',
        brand: 'SkipTheDishes',
        category: 'Gift Cards',
        description: 'Costco wholesale discounted SkipTheDishes food delivery electronic gift cards.',
        packageDetails: '2 x $50 Digital Gift Cards ($100 Value)',
        quantity: 1,
        unitPrice: 79.99,
        totalPrice: 79.99,
        discount: 20.00,
        orderId: 'rcpt_gc_1',
        orderNumber: '3109928114',
        orderDate: '2025-01-28',
        orderType: 'Online',
        warehouseLocation: 'Costco.com (Digital Delivery)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.ca/skipthedishes-gift-card.html',
        isEnriched: true,
      },
      {
        id: 'item_gc_4',
        itemId: '1523400',
        rawName: 'UBER & UBER EATS $100 GC',
        productName: 'Uber & Uber Eats $100 Gift Card (2 x $50)',
        brand: 'Uber',
        category: 'Gift Cards',
        description: 'Costco wholesale discounted Uber ride and food delivery electronic gift cards.',
        packageDetails: '2 x $50 Digital Gift Cards ($100 Value)',
        quantity: 1,
        unitPrice: 79.99,
        totalPrice: 79.99,
        discount: 20.00,
        orderId: 'rcpt_gc_1',
        orderNumber: '3109928114',
        orderDate: '2025-01-28',
        orderType: 'Online',
        warehouseLocation: 'Costco.com (Digital Delivery)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/uber-gift-cards.html',
        isEnriched: true,
      },
    ],
  },
  {
    id: 'rcpt_wh_3',
    orderNumber: '00122 0004 00712',
    orderDate: '2024-06-12',
    orderType: 'Warehouse',
    warehouseLocation: 'Costco Wholesale #122 (San Jose, CA)',
    paymentCard: 'Costco Anywhere Visa ****4128',
    subtotal: 57.85,
    tax: 4.92,
    total: 62.77,
    sourceType: 'sample',
    fileName: 'sample_sanjose_june2024.jpg',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 240).toISOString(),
    items: [
      {
        id: 'item_wh3_1',
        itemId: '1142277',
        rawName: 'KS ORG EVOO 2L',
        productName: 'Kirkland Signature Organic Extra Virgin Olive Oil, 2 L',
        brand: 'Kirkland Signature',
        category: 'Pantry & Oils',
        description: 'USDA certified organic cold-extracted extra virgin olive oil in a 2-liter bottle, harvested from Mediterranean olives.',
        packageDetails: '2 Liters (67.6 fl oz)',
        quantity: 1,
        unitPrice: 18.99,
        totalPrice: 18.99,
        orderId: 'rcpt_wh_3',
        orderNumber: '00122 0004 00712',
        orderDate: '2024-06-12',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #122 (San Jose, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/kirkland-signature-organic-extra-virgin-olive-oil%2c-2-l.product.100334842.html',
        isEnriched: true,
      },
      {
        id: 'item_wh3_2',
        itemId: '2010',
        rawName: 'ROTISSERIE CHICKEN',
        productName: 'Kirkland Signature Fresh Roasted Rotisserie Chicken',
        brand: 'Kirkland Signature',
        category: 'Fresh Deli & Meat',
        description: 'Costco staple 3 lb whole roasted chicken seasoned and hot from the rotisserie.',
        packageDetails: '3 lbs approx',
        quantity: 1,
        unitPrice: 4.99,
        totalPrice: 4.99,
        orderId: 'rcpt_wh_3',
        orderNumber: '00122 0004 00712',
        orderDate: '2024-06-12',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #122 (San Jose, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.google.com/search?q=Costco+item+2010+rotisserie+chicken',
        isEnriched: true,
      },
      {
        id: 'item_wh3_3',
        itemId: '1094091',
        rawName: "RAO'S MARINARA 2/28OZ",
        productName: "Rao's Homemade All Natural Marinara Sauce, 28 oz, 2-count",
        brand: "Rao's Homemade",
        category: 'Pantry & Condiments',
        description: 'Slow-simmered Italian plum tomato sauce with fresh basil, oregano, and garlic. 2 x 28 oz jars.',
        packageDetails: '2 x 28 oz Jars (56 oz Total)',
        quantity: 1,
        unitPrice: 10.99,
        totalPrice: 10.99,
        orderId: 'rcpt_wh_3',
        orderNumber: '00122 0004 00712',
        orderDate: '2024-06-12',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #122 (San Jose, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/raos-homemade-marinara-sauce.html',
        isEnriched: true,
      },
      {
        id: 'item_wh3_4',
        itemId: '1337424',
        rawName: 'KS BATH TISSUE 30PK',
        productName: 'Kirkland Signature 2-Ply Bath Tissue, 30 Rolls',
        brand: 'Kirkland Signature',
        category: 'Household & Paper Goods',
        description: 'Soft, absorbent 2-ply bath tissue with 380 sheets per roll.',
        packageDetails: '30 Rolls / 380 Sheets',
        quantity: 1,
        unitPrice: 20.99,
        totalPrice: 20.99,
        orderId: 'rcpt_wh_3',
        orderNumber: '00122 0004 00712',
        orderDate: '2024-06-12',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #122 (San Jose, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/kirkland-signature-bath-tissue.product.100645875.html',
        isEnriched: true,
      },
      {
        id: 'item_wh3_5',
        itemId: '30669',
        rawName: 'ORGANIC BANANAS 3LB',
        productName: 'Organic Whole Bananas, 3 lbs',
        brand: 'Del Monte / Chiquita',
        category: 'Fresh Produce',
        description: 'USDA Certified Organic fresh yellow bananas in a 3 lb bag.',
        packageDetails: '3 lb bag',
        quantity: 1,
        unitPrice: 1.89,
        totalPrice: 1.89,
        orderId: 'rcpt_wh_3',
        orderNumber: '00122 0004 00712',
        orderDate: '2024-06-12',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #122 (San Jose, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/organic-bananas.product.100412839.html',
        isEnriched: true,
      },
    ],
  },
  {
    id: 'rcpt_wh_4',
    orderNumber: '00471 0019 00418',
    orderDate: '2024-08-25',
    orderType: 'Warehouse',
    warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
    paymentCard: 'Costco Anywhere Visa ****4128',
    subtotal: 59.90,
    tax: 4.88,
    total: 64.78,
    sourceType: 'sample',
    fileName: 'sample_foster_city_aug2024.jpg',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    items: [
      {
        id: 'item_wh4_1',
        itemId: '2010',
        rawName: 'ROTISSERIE CHICKEN',
        productName: 'Kirkland Signature Fresh Roasted Rotisserie Chicken',
        brand: 'Kirkland Signature',
        category: 'Fresh Deli & Meat',
        description: 'Costco staple 3 lb whole roasted chicken seasoned and hot from the rotisserie.',
        packageDetails: '3 lbs approx',
        quantity: 1,
        unitPrice: 4.99,
        totalPrice: 4.99,
        orderId: 'rcpt_wh_4',
        orderNumber: '00471 0019 00418',
        orderDate: '2024-08-25',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.google.com/search?q=Costco+item+2010+rotisserie+chicken',
        isEnriched: true,
      },
      {
        id: 'item_wh4_2',
        itemId: '1094091',
        rawName: "RAO'S MARINARA 2/28OZ",
        productName: "Rao's Homemade All Natural Marinara Sauce, 28 oz, 2-count",
        brand: "Rao's Homemade",
        category: 'Pantry & Condiments',
        description: 'Slow-simmered Italian plum tomato sauce. Instant $2.00 manufacturer coupon rebate applied.',
        packageDetails: '2 x 28 oz Jars (56 oz Total)',
        quantity: 1,
        unitPrice: 8.99,
        totalPrice: 8.99,
        discount: 2.00,
        orderId: 'rcpt_wh_4',
        orderNumber: '00471 0019 00418',
        orderDate: '2024-08-25',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/raos-homemade-marinara-sauce.html',
        isEnriched: true,
      },
      {
        id: 'item_wh4_3',
        itemId: '1337424',
        rawName: 'KS BATH TISSUE 30PK',
        productName: 'Kirkland Signature 2-Ply Bath Tissue, 30 Rolls',
        brand: 'Kirkland Signature',
        category: 'Household & Paper Goods',
        description: 'Soft, absorbent 2-ply bath tissue with 380 sheets per roll.',
        packageDetails: '30 Rolls / 380 Sheets',
        quantity: 1,
        unitPrice: 21.49,
        totalPrice: 21.49,
        orderId: 'rcpt_wh_4',
        orderNumber: '00471 0019 00418',
        orderDate: '2024-08-25',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/kirkland-signature-bath-tissue.product.100645875.html',
        isEnriched: true,
      },
      {
        id: 'item_wh4_4',
        itemId: '30669',
        rawName: 'ORGANIC BANANAS 3LB',
        productName: 'Organic Whole Bananas, 3 lbs',
        brand: 'Del Monte / Chiquita',
        category: 'Fresh Produce',
        description: 'USDA Certified Organic fresh yellow bananas in a 3 lb bag.',
        packageDetails: '3 lb bag',
        quantity: 1,
        unitPrice: 1.99,
        totalPrice: 1.99,
        orderId: 'rcpt_wh_4',
        orderNumber: '00471 0019 00418',
        orderDate: '2024-08-25',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/organic-bananas.product.100412839.html',
        isEnriched: true,
      },
      {
        id: 'item_wh4_5',
        itemId: '1714597',
        rawName: 'KS CREATE-A-SIZE PT 12CT',
        productName: 'Kirkland Signature Create-a-Size Paper Towels, 12 Rolls',
        brand: 'Kirkland Signature',
        category: 'Household & Paper Goods',
        description: '12 rolls of 2-ply premium embossed paper towels with 160 sheets per roll.',
        packageDetails: '12 Rolls / 160 Sheets',
        quantity: 1,
        unitPrice: 22.44,
        totalPrice: 22.44,
        orderId: 'rcpt_wh_4',
        orderNumber: '00471 0019 00418',
        orderDate: '2024-08-25',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/kirkland-signature-paper-towels.product.100645877.html',
        isEnriched: true,
      },
    ],
  },
  {
    id: 'rcpt_wh_5',
    orderNumber: '00471 0031 00119',
    orderDate: '2025-02-20',
    orderType: 'Warehouse',
    warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
    paymentCard: 'Costco Anywhere Visa ****4128',
    subtotal: 65.65,
    tax: 5.62,
    total: 71.27,
    sourceType: 'sample',
    fileName: 'sample_foster_city_feb2025.jpg',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    items: [
      {
        id: 'item_wh5_1',
        itemId: '1142277',
        rawName: 'KS ORG EVOO 2L',
        productName: 'Kirkland Signature Organic Extra Virgin Olive Oil, 2 L',
        brand: 'Kirkland Signature',
        category: 'Pantry & Oils',
        description: 'USDA certified organic cold-extracted extra virgin olive oil in a 2-liter bottle, harvested from Mediterranean olives.',
        packageDetails: '2 Liters (67.6 fl oz)',
        quantity: 1,
        unitPrice: 22.99,
        totalPrice: 22.99,
        orderId: 'rcpt_wh_5',
        orderNumber: '00471 0031 00119',
        orderDate: '2025-02-20',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/kirkland-signature-organic-extra-virgin-olive-oil%2c-2-l.product.100334842.html',
        isEnriched: true,
      },
      {
        id: 'item_wh5_2',
        itemId: '2010',
        rawName: 'ROTISSERIE CHICKEN',
        productName: 'Kirkland Signature Fresh Roasted Rotisserie Chicken',
        brand: 'Kirkland Signature',
        category: 'Fresh Deli & Meat',
        description: 'Costco staple 3 lb whole roasted chicken seasoned and hot from the rotisserie.',
        packageDetails: '3 lbs approx',
        quantity: 1,
        unitPrice: 4.99,
        totalPrice: 4.99,
        orderId: 'rcpt_wh_5',
        orderNumber: '00471 0031 00119',
        orderDate: '2025-02-20',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.google.com/search?q=Costco+item+2010+rotisserie+chicken',
        isEnriched: true,
      },
      {
        id: 'item_wh5_3',
        itemId: '1094091',
        rawName: "RAO'S MARINARA 2/28OZ",
        productName: "Rao's Homemade All Natural Marinara Sauce, 28 oz, 2-count",
        brand: "Rao's Homemade",
        category: 'Pantry & Condiments',
        description: 'Slow-simmered Italian plum tomato sauce with fresh basil, oregano, and garlic. 2 x 28 oz jars.',
        packageDetails: '2 x 28 oz Jars (56 oz Total)',
        quantity: 1,
        unitPrice: 12.49,
        totalPrice: 12.49,
        orderId: 'rcpt_wh_5',
        orderNumber: '00471 0031 00119',
        orderDate: '2025-02-20',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/raos-homemade-marinara-sauce.html',
        isEnriched: true,
      },
      {
        id: 'item_wh5_4',
        itemId: '1337424',
        rawName: 'KS BATH TISSUE 30PK',
        productName: 'Kirkland Signature 2-Ply Bath Tissue, 30 Rolls',
        brand: 'Kirkland Signature',
        category: 'Household & Paper Goods',
        description: 'Soft, absorbent 2-ply bath tissue with 380 sheets per roll.',
        packageDetails: '30 Rolls / 380 Sheets',
        quantity: 1,
        unitPrice: 22.99,
        totalPrice: 22.99,
        orderId: 'rcpt_wh_5',
        orderNumber: '00471 0031 00119',
        orderDate: '2025-02-20',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/kirkland-signature-bath-tissue.product.100645875.html',
        isEnriched: true,
      },
      {
        id: 'item_wh5_5',
        itemId: '30669',
        rawName: 'ORGANIC BANANAS 3LB',
        productName: 'Organic Whole Bananas, 3 lbs',
        brand: 'Del Monte / Chiquita',
        category: 'Fresh Produce',
        description: 'USDA Certified Organic fresh yellow bananas in a 3 lb bag.',
        packageDetails: '3 lb bag',
        quantity: 1,
        unitPrice: 2.19,
        totalPrice: 2.19,
        orderId: 'rcpt_wh_5',
        orderNumber: '00471 0031 00119',
        orderDate: '2025-02-20',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #471 (Foster City, CA)',
        paymentCard: 'Costco Anywhere Visa ****4128',
        webSourceUrl: 'https://www.costco.com/organic-bananas.product.100412839.html',
        isEnriched: true,
      },
    ],
  },
  {
    id: 'rcpt_return_1',
    orderNumber: '00122 0012 00049',
    orderDate: '2025-02-05',
    orderType: 'Warehouse',
    warehouseLocation: 'Costco Wholesale #122 (San Jose, CA)',
    paymentCard: 'Refund to Visa ****8931',
    subtotal: -169.99,
    tax: -15.72,
    total: -185.71,
    sourceType: 'sample',
    fileName: 'warehouse_return_receipt.jpg',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    isReturn: true,
    items: [
      {
        id: 'item_ret_1',
        itemId: '1643444',
        rawName: '/1643444 KS 3PC WEDGE SET (RETURN)',
        productName: 'Kirkland Signature 3-Piece Golf Wedge Set (Right Hand)',
        brand: 'Kirkland Signature',
        category: 'Sports & Outdoors',
        description: 'Returned item - Member satisfaction refund for golf wedge set.',
        packageDetails: 'Set of 3 Wedges (52, 56, 60)',
        quantity: 1,
        unitPrice: -169.99,
        totalPrice: -169.99,
        orderId: 'rcpt_return_1',
        orderNumber: '00122 0012 00049',
        orderDate: '2025-02-05',
        orderType: 'Warehouse',
        warehouseLocation: 'Costco Wholesale #122 (San Jose, CA)',
        paymentCard: 'Refund to Visa ****8931',
        webSourceUrl: 'https://www.costco.com/kirkland-signature-3-piece-golf-wedge-set.product.100696718.html',
        isEnriched: true,
        isReturn: true,
      },
    ],
  },
];

export const isSampleReceipt = (r: CostcoReceipt): boolean => {
  if (!r) return false;
  if (r.sourceType === 'sample') return true;
  const id = String(r.id || '');
  if (
    id.startsWith('rcpt_wh_') ||
    id.startsWith('rcpt_online_') ||
    id.startsWith('rcpt_gc_') ||
    id.startsWith('rcpt_return_')
  ) {
    return true;
  }
  const fileName = String(r.fileName || '');
  if (
    fileName.includes('sample_foster_city') ||
    fileName.includes('cyberweek_order') ||
    fileName.includes('warehouse_receipt_jan2025') ||
    fileName.includes('costco_egift_order') ||
    fileName.includes('warehouse_return_feb2025')
  ) {
    return true;
  }
  return false;
};
